package com.bcl.netsumap;

import static com.codename1.ui.CN.*;

import com.bcl.netsumap.ui.UI;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class NetsuMap extends Lifecycle {
    @Override
    public void runApp() {
        Toolbar.setGlobalToolbar(true);
        UI ui = new UI();
        ui.splashScreen();
    }

}
